version: '3'
services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    # react
    # command: sh -c 'cd react-sample && yarn start'

    # next
    command: sh -c 'cd next-sample && yarn run dev'
    ports:
      - 3000:3000
    tty: true
