version: '3'
services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd nextjs-gihyo-book && yarn run dev'
    ports:
      - 3000:3000
    tty: true
  storybook:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd nextjs-gihyo-book && yarn storybook'
    ports:
      - 6006:6006
    tty: true
  jsonserver:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd ts-nextbook-json && npm ci && npm start'
    ports:
      - 8000:8000
    tty: true
